config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/:user_id/stamp_cards", to: "stamp_cards#stampit", as: :stampit
  get "/:user_id/your_stamp_cards", to: "stamp_cards#index", as: :stamp_cards
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  resources :pages, only: [:show]
  resources :shops do
    resources :stamp_card_templates, only: %i[new create] do
      resources :stamp_cards, only: %i[show destroy]
    end
  end
end

app/views/shared/_confirmation.html.erb
<div class="swal-icon swal-icon--success">
    <span class="swal-icon--success__line swal-icon--success__line--long"></span>
    <span class="swal-icon--success__line swal-icon--success__line--tip"></span>
    <div class="swal-icon--success__ring"></div>
    <div class="swal-icon--success__hide-corners"></div>
</div>

app/views/shared/_confirmation_modal.html.erb
<div class="modal" tabindex="-1" id="testModal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Confirmation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body modal-confirmation">
        <p class="text-center mb-3">You recieved a new stamp!</p>
        <%= render "shared/confirmation" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_final_stampcard.html.erb
<div class="main-container">
    <div class="thecard" data-controller="stamp-card">
      <div class="front p-3" data-action="click->stamp-card#switchToBack">
        <div class="card-first-line">
          <h2><%= stamp_card.stamp_card_template.shop.name %></h2>
          <i class="fa-solid fa-circle-info" ></i>
        </div>
          <p><%= stamp_card.stamp_card_template.title %></p>
          <div class="img-container">
            <% if stamp_card %>
              <% stamp_card.stamp_amount.times do %>
              <div class="active">
                <%= image_tag image_url("Stamps_black.png")%>
              </div>
              <% end %>

              <% (stamp_card.stamp_card_template.max_stamps - stamp_card.stamp_amount).times do %>
                <div class="inactive">
                  <%= image_tag image_url("Stamps_black.png")%>
                </div>
              <% end %>

            <% else %>
              <% stamp_card_template.max_stamps.times do %>
                <div class="inactive">
                  <%= image_tag image_url("Stamps_black.png")%>
                </div>
              <% end %>
            <% end %>

          </div>
      </div>
      <div class="back p-3" data-action="click->stamp-card#switchToFront">
        <div class="card-first-line">
          <h2><%= stamp_card.stamp_card_template.shop.name %></h2>
          <i class="fa-solid fa-xmark"></i>
        </div>
        <p><%= stamp_card.stamp_card_template.description %></p>

        <div class="last-line">
          <p>Card expires on: <%= stamp_card.stamp_card_template.expiration_date %></p>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar_bottom.html.erb
<div class="nav-bot sticky-bottom">
  <%= link_to root_path, style: "text-decoration: none" do %>
    <div class="nav-bot-logo">
      <i class="fa-solid fa-house"></i>
      <p>Home</p>
    </div>
  <% end %>
    <div class="nav-bot-logo" data-bs-toggle="modal" data-bs-target="#qr-code-modal">
      <i class="fa-solid fa-qrcode"></i>
      <p>QR Code</p>
    </div>
  <%= link_to stamp_cards_path(current_user.id), style: "text-decoration: none" do  %>
    <div class="nav-bot-logo">
      <i class="fa-solid fa-stamp"></i>
      <p>My stamps</p>
    </div>
  <% end %>
  <%= link_to shops_path, style: "text-decoration: none" do  %>
    <div class="nav-bot-logo">
      <i class="fa-solid fa-magnifying-glass"></i>
      <p>Search</p>
    </div>
  <% end %>
</div>
<div data-controller="user-subscription" data-user-subscription-user-id-value="<%= current_user.id %>" class="modal fade" tabindex="-1" id="qr-code-modal">
  <div class="modal-dialog modal-fullscreen">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">My QR Code</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="qr-code-card d-flex align-items-center justify-content-center">
            <div class="qr-code">
                <%= cl_image_tag current_user.qrcode.key, style: "border-radius: 8px;"  %>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar_top.html.erb
<nav class="navbar navbar-dark sticky-top">
  <div class="container-fluid" style="height: 54px">

    <button class="navbar-toggler " type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon" style="border-color: none"></span>
    </button>
    <h1 class="" style="margin-bottom: 0; margin-right: 12px; color: white;"><strong>Stamps</strong></h1>
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <%= link_to root_path do %>
          <%# <%= image_tag current_user.profile_img_url, class: "avatar-bordered" %>
        <% end %>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-start flex-grow-1">
          <li class="nav-item my-3">
            <a class="nav-link active" style="text-decoration: none; color: black" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item my-3">
            <a class="nav-link" style="text-decoration: none; color: black" href="/pages/<%= current_user.id %>">QR-Scanner</a>
          </li>
          <li class="nav-item my-4">
          <%= link_to "Logout", destroy_user_session_path, style: "text-decoration: none; color: black", class:"nav-link", data: {turbo_method: :delete} %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_opening_hours.html.erb
<div class="container shop-container my-3">
  <div class="main-container-shop">
    <div class="thecard-shop">
      <div class="front-shop p-3">
        <div class="card-first-line-shop">
          <h4>Opening Hours</h4>
        </div>
        <div class="date-and-hour d-flex justify-content-between">
          <p class="py-2 flex-grow-1">Mon - Sun</p>
          <p class="py-2"><i>11 AM - 9 PM</i></p>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<%= form_with url: shops_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a place"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

app/views/shared/_stampcard.html.erb
<div class="container">
  <div class="main-container">
    <div class="thecard" data-controller="stamp-card">
      <div class="front p-3" data-action="click->stamp-card#switchToBack">
        <div class="card-first-line">
          <h2><%= shop.name %></h2>
          <i class="fa-solid fa-circle-info" ></i>
        </div>
          <p><%= stamp_card_template.title %></p>
          <div class="img-container">
            <% if stamp_card %>
              <% stamp_card.stamp_amount.times do %>
              <div class="active">
                <%= image_tag image_url("Stamps_black.png")%>
              </div>
              <% end %>

              <% (stamp_card_template.max_stamps - stamp_card.stamp_amount).times do %>
                <div class="inactive">
                  <%= image_tag image_url("Stamps_black.png")%>
                </div>
              <% end %>

            <% else %>
              <% stamp_card_template.max_stamps.times do %>
                <div class="inactive">
                  <%= image_tag image_url("Stamps_black.png")%>
                </div>
              <% end %>
            <% end %>

          </div>
      </div>
      <div class="back p-3" data-action="click->stamp-card#switchToFront">
        <div class="card-first-line">
          <h2><%= shop.name %></h2>
          <i class="fa-solid fa-xmark"></i>
        </div>
        <p><%= stamp_card_template.description %></p>

        <div class="last-line">
          <p>Card expires on: <%= stamp_card_template.expiration_date %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_stampcard_confirmation.html.erb
<div class="container">
  <div class="main-container">
    <div class="thecard" data-controller="stamp-card">
      <div class="front p-3" data-action="click->stamp-card#switchToBack">
        <div class="card-first-line">
          <h2><%= shop.name %></h2>
          <i class="fa-solid fa-circle-info" ></i>
        </div>
          <p><%= stamp_card_template.title %></p>
          <div class="img-container">
            <img class="active" src="" alt="">
            <img class="active" src="" alt="">
            <img class="active" src="" alt="">
            <img class="confirmed" src="" alt="">
            <img src="" alt="">
            <img src="" alt="">
            <img src="" alt="">
            <img src="" alt="">
            <img src="" alt="">
            <img src="" alt="">

          </div>
      </div>
      <div class="back p-3" data-action="click->stamp-card#switchToFront">
        <div class="card-first-line">
          <h2><%= shop.name %></h2>
          <i class="fa-solid fa-xmark"></i>
        </div>
        <p><%= stamp_card_template.description %></p>

        <div class="last-line">
          <p>Card expires on: <%= stamp_card_template.expiration_date %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_stampcard_index.html.erb
<div class="container">
  <div class="main-container">
    <div class="thecard" data-controller="stamp-card">
      <div class="front p-3" data-action="click->stamp-card#switchToBack">
        <div class="card-first-line">
          <h2><%= shop.name %></h2>
          <i class="fa-solid fa-circle-info" ></i>
        </div>
          <p><%= stamp_card_template.title %></p>
          <div class="img-container">
            <% if stamp_card %>
              <% stamp_card.stamp_amount.times do %>
                <img class="active" src="" alt="">
              <% end %>

              <% (stamp_card_template.max_stamps - stamp_card.stamp_amount).times do %>
                <img src="" alt="">
              <% end %>

            <% else %>
              <% stamp_card_template.max_stamps.times do %>
                <img src="" alt="">
              <% end %>
            <% end %>

          </div>
      </div>
      <div class="back p-3" data-action="click->stamp-card#switchToFront">
        <div class="card-first-line">
          <h2><%= shop.name %></h2>
          <i class="fa-solid fa-xmark"></i>
        </div>
        <p><%= stamp_card_template.description %></p>

        <div class="last-line">
        <p>Card expires on:</p>
          <p> <%= stamp_card_template.expiration_date %></p>
        </div>
      </div>
    </div>
  </div>
</div>